// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Momos.Host.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Momos.Host.Migrations
{
    [DbContext(typeof(MomosDbContext))]
    [Migration("20260924161110_ProjectModel")]
    partial class ProjectModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Momos.Host.Domain.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InspectionReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionReportId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InspectionRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRequestId")
                        .IsUnique();

                    b.ToTable("InspectionReports");
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommitRef")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Focus")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("InspectionRequests");
                });

            modelBuilder.Entity("Momos.Host.Domain.ModelClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Correction")
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectModelId", "Key")
                        .IsUnique();

                    b.ToTable("ModelClaims");
                });

            modelBuilder.Entity("Momos.Host.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppInstallArgs")
                        .HasColumnType("text");

                    b.Property<string>("AppInstallLaunchCommand")
                        .HasColumnType("text");

                    b.Property<string>("AppInstallPlatform")
                        .HasColumnType("text");

                    b.Property<string>("AppInstallerUri")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Momos.Host.Domain.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCommit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decisions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Intents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ModelVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Patterns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Relations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId");

                    b.HasIndex("ProjectId", "ModelVersion")
                        .IsUnique();

                    b.ToTable("ProjectModels");
                });

            modelBuilder.Entity("Momos.Host.Domain.ToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("InspectionRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRequestId");

                    b.ToTable("ToolCalls");
                });

            modelBuilder.Entity("Momos.Host.Domain.Finding", b =>
                {
                    b.HasOne("Momos.Host.Domain.InspectionReport", null)
                        .WithMany("Findings")
                        .HasForeignKey("InspectionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionReport", b =>
                {
                    b.HasOne("Momos.Host.Domain.InspectionRequest", null)
                        .WithOne()
                        .HasForeignKey("Momos.Host.Domain.InspectionReport", "InspectionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionRequest", b =>
                {
                    b.HasOne("Momos.Host.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.ModelClaim", b =>
                {
                    b.HasOne("Momos.Host.Domain.ProjectModel", null)
                        .WithMany("Claims")
                        .HasForeignKey("ProjectModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.ProjectModel", b =>
                {
                    b.HasOne("Momos.Host.Domain.InspectionRequest", null)
                        .WithMany()
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Momos.Host.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.ToolCall", b =>
                {
                    b.HasOne("Momos.Host.Domain.InspectionRequest", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("InspectionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionReport", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Momos.Host.Domain.InspectionRequest", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("Momos.Host.Domain.ProjectModel", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
