<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="IronHive.Agent" />
    <PackageReference Include="IronHive.Core" />
    <PackageReference Include="IronHive.Providers.OpenAI.Compatible" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

</Project>
